name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Retrieve .env from secrets
      run: echo "${{ secrets.DOT_ENV_DEV }}" > .env

    - name: Log in to Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

    - name: Build Docker image
      run: |
        docker buildx build -f Dockerfile.heroku -t registry.heroku.com/sa-idl-dev/web .

    - name: Set Heroku stack to container
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku stack:set container --app sa-idl-dev
    

    - name: Push Docker image to Heroku
      run: docker push registry.heroku.com/sa-idl-dev/web

    - name: Release to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release web --app sa-idl-dev
